name: pre-cat
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.23.5
  - scipy
  - matplotlib
  - pydicom
  - pandas
  - streamlit=1.40.0
  - plotly
  - pillow
  - tqdm
  - pyyaml
  - scikit-learn
  - seaborn
  - sigpy 
  - h5py
  - tornado=6.1
  - pip:
    - streamlit-drawable-canvas
    - bmctool==0.5.0