####################################################################################
# ------ Simulation settings for (py)pulseq-cest BlochMcConnell simulations ------ #
# ------------------------ https://pulseq-cest.github.io/ ------------------------ #
####################################################################################
# Simulation parameters for Cr/PCr @ 3T (basline)
# - 2 CEST pools
# - Water pool as in a phantom

###### Pool settings
#         f: relative pool size fraction (float)
#        t1: longitudinal relaxation time T1 = 1/R1 [s] (float)
#        t2: transversal relaxation time T2 = 1/R2 [s] (float)
#         k: exchange rate [Hz] to water pool (MT and CEST pools only) (float)
#        dw: chemical shift (delta omega) relative to water [ppm] (MT and CEST pools only) (float)
# lineshape: lineshape of the MT Pool ('Lorentzian', 'SuperLorentzian' or 'None') (str)

### Water pool
water_pool: {
  f: 1.0,
  t1: 4.0,
  t2: 2.0
}

### CEST pool(s)
cest_pool: {
  'creatine': {
    f: 4.856e-4,
    t1: 1.37,
    t2: 0.02,
    k: 1100,
    dw: 2.0
  },
  'phosphocreatine': {
    f: 4.856e-4,
    t1: 3.90,
    t2: 0.02,
    k: 200,
    dw: 2.0
  }
}

###### Scanner settings
#       b0: field strength [T] (float)
#    gamma: gyromagnetic ratio [rad / uT], default is 267.5153 (float)
# b0_inhom: field inhomogeneity [ppm], default is 0.0 (float)
#   rel_b1: relative amp inhomogeneity, default is 1.0 (float)
b0: 3
gamma: 267.5153
b0_inhom: 0.0
rel_b1: 1

##### Additional simulation settings
#           verbose: verbose output, default is False (bool)
#    reset_init_mag: True to reset magnetization after each readout, default is True (bool)
#             scale: relative magnetization after reset of magnetization, default is 1 (float)
# max_pulse_samples: maximum number of samples for each shaped rf pulse, default is 500 (int)
verbose: False
reset_init_mag: True
scale: 1
max_pulse_samples: 300